#!/usr/bin/env bash
set -euo pipefail

export MACHINE_LEARNING_CACHE_FOLDER="${MACHINE_LEARNING_CACHE_FOLDER:-/Volumes/SKHynix/immich-ml-cache}"
export MACHINE_LEARNING_MODEL_TTL="${MACHINE_LEARNING_MODEL_TTL:-0}"
export MACHINE_LEARNING_MODEL_TTL_CLIP="${MACHINE_LEARNING_MODEL_TTL_CLIP:-$MACHINE_LEARNING_MODEL_TTL}"
export MACHINE_LEARNING_MODEL_TTL_FACIAL_RECOGNITION="${MACHINE_LEARNING_MODEL_TTL_FACIAL_RECOGNITION:-$MACHINE_LEARNING_MODEL_TTL}"
export MACHINE_LEARNING_MODEL_TTL_OCR="${MACHINE_LEARNING_MODEL_TTL_OCR:-$MACHINE_LEARNING_MODEL_TTL}"
export MACHINE_LEARNING_PROVIDERS__CLIP="${MACHINE_LEARNING_PROVIDERS__CLIP:-CPUExecutionProvider}"
export MACHINE_LEARNING_PROVIDERS__OCR="${MACHINE_LEARNING_PROVIDERS__OCR:-CPUExecutionProvider}"
export MACHINE_LEARNING_PROVIDERS__FACIAL_RECOGNITION="${MACHINE_LEARNING_PROVIDERS__FACIAL_RECOGNITION:-CoreMLExecutionProvider,CPUExecutionProvider}"
export MACHINE_LEARNING_COREML_RETRY_CPU_ON_FAILURE="${MACHINE_LEARNING_COREML_RETRY_CPU_ON_FAILURE:-true}"
export IMMICH_LOG_LEVEL="${IMMICH_LOG_LEVEL:-debug}"
export IMMICH_HOST="${IMMICH_HOST:-0.0.0.0}"
export IMMICH_PORT="${IMMICH_PORT:-3003}"

exec uv run uvicorn immich_ml.main:app --host "$IMMICH_HOST" --port "$IMMICH_PORT"
